DROP TABLE IF EXISTS T_LUGGAGE_INFO
;
CREATE TABLE T_LUGGAGE_INFO (
  TRIP_PLAN_NAME VARCHAR
  ,  LUGGAGE_NO SMALLINT
  ,  LUGGAGE_COUNT SMALLINT
  ,  BAG_NO CHAR(2)
  ,  LUGGAGE_PREPARED_FLG BOOLEAN
  ,  INS_USER_ID CHAR(8)
  ,  INS_DATE TIMESTAMP(0)
  ,  UPD_USER_ID CHAR(8)
  ,  UPD_DATE TIMESTAMP(0)
)
;
ALTER TABLE T_LUGGAGE_INFO	
    ADD CONSTRAINT PK_T_LUGGAGE_INFO PRIMARY KEY (TRIP_PLAN_NAME, LUGGAGE_NO, BAG_NO, INS_DATE)
;