DROP TABLE IF EXISTS T_TRIP_PLAN
;
CREATE TABLE T_TRIP_PLAN (
  TRIP_PLAN_NAME VARCHAR
  ,  INS_USER_ID CHAR(8)
  ,  INS_DATE TIMESTAMP(0)
  ,  UPD_USER_ID CHAR(8)
  ,  UPD_DATE TIMESTAMP(0)
)
;
ALTER TABLE T_TRIP_PLAN	
    ADD CONSTRAINT PK_T_TRIP_PLAN PRIMARY KEY (TRIP_PLAN_NAME)
;